### ISSUE TITLE
"Smart quotes" interferes with other plugins

### ISSUE THREAD

**Issue by sal0max** [N-Parsons/grav-plugin-markdown-typography#2]
The "Smart quotes" setting alters the JavaScript-Code, my [Chart.js++](https://github.com/sal0max/grav-plugin-shortcode-chart-js-plusplus) Plugin generates. Like in the following example to be seen. That way, the chart can't be rendered any more and the page stays empty.

```html
...
<script>var ctx = document.getElementById('canvas');
var aChart = new Chart(ctx, {
type: 'line',
data: {
type: 'line',
labels: ['02.02.2019',' 15.02.2019',' 01.03.2019',' 15.03.2019',' 01.04.2019',' 15.04.2019',' 01.05.2019',' 15.05.2019',' 01.06.2019',' 15.06.2019',' 01.07.2019',' 15.07.2019',' 01.08.2019',' 15.08.2019',' 01.09.2019',' 15.09.2019',' 01.10.2019',' 15.10.2019',' 01.11.2019',' 15.11.2019',' 01.12.2019',' 15.12.2019',' 01.01.2020',' 15.01.2020',' 01.02.2020',' 15.02.2020',' 01.03.2020',' 15.03.2020]<span>“
]
[canvas
id=”</span>chart<span>“
width=”</span>300<span>“
height=”</span>100<span>“
]
[dataset
data=”</span>[1',' 2',' 2',' 2',' 3',' 3',' 4',' 4',' 6',' 5',' 5',' 6',' 7',' 12',' 12',' 12',' 11',' 12',' 12',' 10',' 10',' 9',' 10',' 12',' 11',' 11',' 13',' 16]<span>“
fill=”</span>false<span>“
pointRadius=”</span>5<span>“
pointHoverRadius=”</span>8<span>“
]
[options
legend=”</span>false<span>“
responsive=”</span>tru'],
datasets: []
},
});</script>
...
```

Would be awesome if you'd find a way to prevent everything inside `<script>` blocks to be altered. Apart from this issue, I find your plugin really useful.

**Comment by N-Parsons** [comment]
Thanks for the report, @sal0max.

This issue arises from an interaction between Shortcodes and Markdown processing, so I'll have to dig into it to find a solution, but I should be able to get something to work.

My current best workaround is to wrap the shortcode in a `<div>` so that Markdown processing is disabled for that section of the page.

**Comment by N-Parsons** [comment]
The issue was related to the use of square brackets within Shortcode parameters (eg. `data="[ ... ]"`). I've improved the Regex for Shortcode parameter protection, so this issue has now been fixed.
